version: '3.8'

services:
  monitoring-demo:
    container_name: monitoring-demo
    image: crbhumika/monitoringdemo:latest
    pull_policy: always

  prometheus:
    image: prom/prometheus:v2.27.1
    container_name: prometheus
    restart: unless-stopped
    ports:
     - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
     - monitoring-demo

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
     - "3000:3000"
    volumes:
     - ./grafana:/var/lib/grafana
    environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=admin