global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'monitoring-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitoring-demo:8080']
        labels:
          application: 'Monitoring demo application'